### ISSUE TITLE
Error  TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by TheComputerCat** [halodaga/Proyecto-estructuras#1]
Cuando self.data[i] == 0 en search
![Capture](https://user-images.githubusercontent.com/56846588/80272143-679b5d00-868c-11ea-8b72-6549aadc31ab.PNG)

**Comment by halodaga** [comment]
con qué datos se produce el error ?

**Comment by TheComputerCat** [comment]
con alguna key de jisho, si usted borra el primer elemento de data al hacer la comparacion como que no puede

**Comment by halodaga** [comment]
agregar "if i != 0:" en la linea 61 e identar con cuidado
